import anchor from "@coral-xyz/anchor";
const BN = anchor.BN;
const Program = anchor.Program;
const Wallet = anchor.Wallet;
import { Keypair, PublicKey, LAMPORTS_PER_SOL, Connection, AddressLookupTableProgram } from "@solana/web3.js";
import { expect } from "chai";
import { createHash, randomBytes } from "crypto";
import { readFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { x25519 } from "@noble/curves/ed25519";

const idl = JSON.parse(readFileSync(join(process.cwd(), "app/src/idl/shadow_bid.json"), "utf-8"));

// Known addresses from localnet artifacts (generated by `arcium test --skip-build`)
const SHADOWBID_PROGRAM_ID = new PublicKey("F4tKBoryaS7kaQH2Hh1CxrQDRz4HRipVEztf5p5cT5wf");
const ARCIUM_PROGRAM_ID = new PublicKey("Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ");
const MXE_PDA = new PublicKey("9N9EQ2saugxyFbYysyBRRykc22Efn4F86Aaf8goK2EgF");
const CLUSTER_PDA = new PublicKey("CuTp9LKzoY9hy77TkrickLpVTUFgvnRfQHB9tnhG2ypt");
const MEMPOOL_PDA = new PublicKey("9rUSnh5VrMtRUrJrgAUwcyWvL9NYkscAsDFS5RjPW6Da");
const EXEC_POOL_PDA = new PublicKey("9EDLm5KDKc1Pf8m587kdxPMvQBNETNahcCfHLNcQ1M8W");
const FEE_POOL_PDA = new PublicKey("G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC");
const CLOCK_PDA = new PublicKey("7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot");
const LUT_PDA = new PublicKey("4V5Lrxi7AJ9iWeiNWs8WCtguRrZUrWaUvVox4emBu4SN");

const CLUSTER_OFFSET = 0;

function findPda(seeds: Buffer[], programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(seeds, programId);
}

function findAuctionPda(creator: PublicKey, id: anchor.BN): [PublicKey, number] {
  return findPda(
    [Buffer.from("auction"), creator.toBuffer(), id.toArrayLike(Buffer, "le", 8)],
    SHADOWBID_PROGRAM_ID,
  );
}

function findResultPda(auction: PublicKey): [PublicKey, number] {
  return findPda([Buffer.from("result"), auction.toBuffer()], SHADOWBID_PROGRAM_ID);
}

function findBidPda(auction: PublicKey, bidder: PublicKey): [PublicKey, number] {
  return findPda([Buffer.from("bid"), auction.toBuffer(), bidder.toBuffer()], SHADOWBID_PROGRAM_ID);
}

function findPlatformPda(): [PublicKey, number] {
  return findPda([Buffer.from("platform")], SHADOWBID_PROGRAM_ID);
}

function findSignPda(): [PublicKey, number] {
  return findPda([Buffer.from("ArciumSignerAccount")], SHADOWBID_PROGRAM_ID);
}

function findComputationPda(clusterOffset: number, compOffset: anchor.BN): [PublicKey, number] {
  const clBuf = Buffer.alloc(4);
  clBuf.writeUInt32LE(clusterOffset, 0);
  return findPda(
    [Buffer.from("ComputationAccount"), clBuf, compOffset.toArrayLike(Buffer, "le", 8)],
    ARCIUM_PROGRAM_ID,
  );
}

function findCompDefPda(mxeProgramId: PublicKey, compDefOffset: number): [PublicKey, number] {
  const offsetBuf = Buffer.alloc(4);
  offsetBuf.writeUInt32LE(compDefOffset, 0);
  return findPda(
    [Buffer.from("ComputationDefinitionAccount"), mxeProgramId.toBuffer(), offsetBuf],
    ARCIUM_PROGRAM_ID,
  );
}

function computeCompDefOffset(circuitName: string): number {
  return createHash("sha256").update(circuitName).digest().readUInt32LE(0);
}

function makeCommitment(auction: PublicKey, bidder: PublicKey, amount: number): number[] {
  const salt = randomBytes(16);
  const hash = createHash("sha256")
    .update("shadowbid:v1")
    .update(auction.toBuffer())
    .update(bidder.toBuffer())
    .update(Buffer.from(amount.toString()))
    .update(salt)
    .digest();
  return Array.from(hash);
}

function makeEncryptedBidPlaceholder(amount: number): number[] {
  return Array.from(createHash("sha256").update(`encrypted:${amount}`).digest());
}

const COMP_DEF_OFFSET = computeCompDefOffset("compute_winner");
const [COMP_DEF_PDA] = findCompDefPda(SHADOWBID_PROGRAM_ID, COMP_DEF_OFFSET);
const [SIGN_PDA] = findSignPda();

describe("shadowbid compute flow", () => {
  const connection = new Connection("http://127.0.0.1:8899", "confirmed");
  const deployer = Keypair.fromSecretKey(
    Buffer.from(JSON.parse(readFileSync(homedir() + "/.config/solana/id.json", "utf-8"))),
  );
  const wallet = new Wallet(deployer);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: "confirmed" });
  anchor.setProvider(provider);

  const program = new Program(idl as anchor.Idl, provider);

  const BIDDER_COUNT = 8;
  const bidders: Keypair[] = [];
  const bidderX25519Keys: { secretKey: Uint8Array; publicKey: Uint8Array }[] = [];

  let computeAuctionPda: PublicKey;
  let computeResultPda: PublicKey;
  let bidPdas: PublicKey[];

  before(async function () {
    this.timeout(60_000);
    for (let i = 0; i < BIDDER_COUNT; i++) {
      const kp = Keypair.generate();
      bidders.push(kp);
      const sig = await provider.connection.requestAirdrop(kp.publicKey, 10 * LAMPORTS_PER_SOL);
      await provider.connection.confirmTransaction(sig);
      // Generate x25519 keypair for Arcium encryption
      const xSecret = x25519.utils.randomPrivateKey();
      const xPublic = x25519.getPublicKey(xSecret);
      bidderX25519Keys.push({ secretKey: xSecret, publicKey: xPublic });
    }
  });

  it("initializes platform config", async () => {
    const [platformPda] = findPlatformPda();
    const existing = await (program.account as any).platformConfig.fetchNullable(platformPda);
    if (existing) return;

    await program.methods
      .initializePlatform()
      .accounts({ authority: deployer.publicKey })
      .rpc();

    const config = await (program.account as any).platformConfig.fetch(platformPda);
    expect(config.authority.toBase58()).to.equal(deployer.publicKey.toBase58());
  });

  it("initializes compute winner computation definition", async function () {
    this.timeout(30_000);

    const existing = await provider.connection.getAccountInfo(COMP_DEF_PDA);
    if (existing) {
      console.log("  comp def already initialized, skipping");
      return;
    }

    await program.methods
      .initComputeWinnerCompDef()
      .accounts({
        payer: deployer.publicKey,
        mxeAccount: MXE_PDA,
        compDefAccount: COMP_DEF_PDA,
        addressLookupTable: LUT_PDA,
        lutProgram: AddressLookupTableProgram.programId,
        arciumProgram: ARCIUM_PROGRAM_ID,
      })
      .rpc();
  });

  it("creates auction, submits 8 bids, closes, triggers compute, and settles", async function () {
    this.timeout(180_000);

    const slot = await connection.getSlot({ commitment: "confirmed" });
    const blockTime = await connection.getBlockTime(slot);
    // Use block time to stay in sync with the validator's clock
    const now = blockTime ?? Math.floor(Date.now() / 1000);
    const startTime = now - 300;
    const endTime = now + 15;
    const settlementDeadline = now + 3600;
    const auctionId = new BN(200 + Math.floor(Math.random() * 1000));

    const [auctionPda] = findAuctionPda(deployer.publicKey, auctionId);
    computeAuctionPda = auctionPda;
    const [resultPda] = findResultPda(computeAuctionPda);
    computeResultPda = resultPda;

    await program.methods
      .createAuction(
        auctionId,
        "Compute Flow Test",
        "Testing full confidential compute flow",
        "SOL",
        new BN(100_000_000),
        new BN(10_000_000),
        new BN(startTime),
        new BN(endTime),
        new BN(settlementDeadline),
        { mock: {} },
      )
      .accounts({ creator: deployer.publicKey })
      .rpc();

    const created = await (program.account as any).auction.fetch(computeAuctionPda);
    expect(created.title).to.equal("Compute Flow Test");

    const amounts = bidders.map((_, i) => 100_000_000 + i * 10_000_000);

    await Promise.all(
      bidders.map((bidder, i) =>
        program.methods
          .submitBidCommitment(
            makeCommitment(computeAuctionPda, bidder.publicKey, amounts[i]),
            Array.from(bidderX25519Keys[i].publicKey),
            new BN(12345 + i),
            makeEncryptedBidPlaceholder(amounts[i]),
            makeEncryptedBidPlaceholder(amounts[i]),
            makeEncryptedBidPlaceholder(amounts[i]),
            makeEncryptedBidPlaceholder(amounts[i]),
            makeEncryptedBidPlaceholder(1),
          )
          .accounts({ bidder: bidder.publicKey, auction: computeAuctionPda })
          .signers([bidder])
          .rpc(),
      ),
    );

    const afterBids = await (program.account as any).auction.fetch(computeAuctionPda);
    expect(afterBids.bidCount).to.equal(BIDDER_COUNT);

    bidPdas = bidders.map((b) => findBidPda(computeAuctionPda, b.publicKey)[0]);

    // Wait for block time to pass end_time
    const waitStart = Date.now();
    while (true) {
      const currentSlot = await connection.getSlot({ commitment: "confirmed" });
      const currentBlockTime = await connection.getBlockTime(currentSlot);
      if (currentBlockTime && currentBlockTime > endTime) break;
      const elapsed = Math.floor((Date.now() - waitStart) / 1000);
      console.log(`  waiting (block=${currentBlockTime}, end=${endTime}, elapsed=${elapsed}s)...`);
      await new Promise((r) => setTimeout(r, 3000));
      if (elapsed > 60) throw new Error("Timeout waiting for end_time");
    }

    await program.methods
      .closeBidding()
      .accounts({ closer: deployer.publicKey, auction: computeAuctionPda })
      .rpc();

    const closed = await (program.account as any).auction.fetch(computeAuctionPda);
    expect(Object.keys(closed.status)[0]).to.equal("closed");

    const computationOffset = new BN(Date.now() % 100000);
    const [computationPda] = findComputationPda(CLUSTER_OFFSET, computationOffset);

    await program.methods
      .triggerConfidentialCompute(computationOffset)
      .accounts({
        payer: deployer.publicKey,
        signPdaAccount: SIGN_PDA,
        auction: computeAuctionPda,
        result: computeResultPda,
        mxeAccount: MXE_PDA,
        mempoolAccount: MEMPOOL_PDA,
        executingPool: EXEC_POOL_PDA,
        computationAccount: computationPda,
        compDefAccount: COMP_DEF_PDA,
        clusterAccount: CLUSTER_PDA,
        poolAccount: FEE_POOL_PDA,
        clockAccount: CLOCK_PDA,
        arciumProgram: ARCIUM_PROGRAM_ID,
      })
      .remainingAccounts(
        bidPdas.map((pda) => ({ pubkey: pda, isWritable: false, isSigner: false })),
      )
      .rpc();

    const finalizing = await (program.account as any).auction.fetch(computeAuctionPda);
    expect(Object.keys(finalizing.status)[0]).to.equal("finalizing");

    // Poll for computation finalization
    console.log("  waiting for computation to finalize...");
    const pollStart = Date.now();
    const pollTimeout = 60_000;
    let finalized = false;

    while (Date.now() - pollStart < pollTimeout) {
      await new Promise((r) => setTimeout(r, 2000));
      try {
        const accInfo = await connection.getAccountInfo(computationPda);
        if (accInfo && accInfo.data.length > 8) {
          const discriminator = accInfo.data.subarray(0, 8);
          const finalizedDisc = Buffer.from([
            0x47, 0xbd, 0x4e, 0x59, 0xaf, 0x9f, 0x9f, 0x8c,
          ]);
          if (discriminator.equals(finalizedDisc)) {
            finalized = true;
            console.log("  computation finalized!");
            break;
          }
        }
      } catch {
        // retry
      }
    }

    if (finalized) {
      await new Promise((r) => setTimeout(r, 3000));

      const auctionAfter = await (program.account as any).auction.fetch(computeAuctionPda);
      const statusKey = Object.keys(auctionAfter.status)[0];
      console.log(`  auction status after compute: ${statusKey}`);

      if (statusKey === "finalized" || statusKey === "reserveNotMet") {
        const result = await (program.account as any).auctionResult.fetch(computeResultPda);
        expect(result.finalized).to.be.true;
        console.log(`  winner: ${result.winner.toBase58()}, amount: ${result.winningAmount}`);

        await program.methods
          .markSettlementCompleted()
          .accounts({ creator: deployer.publicKey, auction: computeAuctionPda })
          .rpc();

        const settled = await (program.account as any).auction.fetch(computeAuctionPda);
        expect(settled.settlementCompleted).to.be.true;
        console.log("  settlement completed");
      } else {
        console.log(`  callback not yet processed (status: ${statusKey})`);
      }
    } else {
      console.log("  computation did not finalize within timeout");
      const st = await (program.account as any).auction.fetch(computeAuctionPda);
      console.log(`  final auction status: ${Object.keys(st.status)[0]}`);
    }
  });
});
